services:
  eclipsejdtls:
    build:
      dockerfile: ./packages/examples/resources/eclipse.jdt.ls/Dockerfile
      context: ../../../..
      # requires "Use containerd for pulling and storing images" in Docker Desktop
      platforms:
        - "linux/amd64"
        # pre-built volta binaries are currently unavailable for linux/arm64, will change with v2.0.0
        # - "linux/arm64"
    platform: linux/amd64
    command: [
      "bash", "-c", "npm i && npm run start:example:server:jdtls"
    ]
    ports:
      - 30003:30003
    working_dir: /home/mlc
    container_name: eclipsejdtls
