services:
  groovyls:
    build:
      dockerfile: ./packages/examples/resources/groovy/Dockerfile
      context: ../../../..
      # requires "Use containerd for pulling and storing images" in Docker Desktop
      platforms:
        - "linux/amd64"
        # pre-built volta binaries are currently unavailable for linux/arm64, will change with v2.0.0
        # - "linux/arm64"
    platform: linux/amd64
    command: [
      "bash", "-c", "npm i && npm run start:example:server:groovy"
    ]
    ports:
      - 30002:30002
    working_dir: /home/gradle/mlc
    container_name: groovyls
